Repository ossrs/srs, pull requests merged in 2022-03, with the labels that each got.

#2914 Security: Enable CIDR for allow/deny play/publish
  trunk/conf/full.conf
  trunk/src/app/srs_app_security.cpp
  trunk/src/app/srs_app_security.hpp
  trunk/src/protocol/srs_protocol_utility.cpp
  trunk/src/protocol/srs_protocol_utility.hpp
  trunk/src/utest/srs_utest_rtmp.cpp
Labels: Feature

#2943 SRT: Fix typo in libsrt build options
  trunk/auto/depends.sh
Labels: Bug

#2908 SRT: url supports multiple QueryStrings
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version4.hpp
  trunk/src/srt/srt_conn.cpp
  trunk/src/srt/srt_conn.hpp
  trunk/src/srt/srt_handle.cpp
  trunk/src/utest/srs_utest_srt.cpp
  trunk/src/utest/srs_utest_srt.hpp
Labels: Feature

#2928 Fix parse_file function did not handle err
  trunk/src/app/srs_app_config.cpp
Labels: Enhancement
