Repository ossrs/srs, pull requests merged in 2023-12, with the labels that each got.

#3902 Security: Support IP whitelist for HTTP-FLV, HLS, WebRTC, and SRT. v5.0.202 v6.0.104
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_http_static.cpp
  trunk/src/app/srs_app_http_static.hpp
  trunk/src/app/srs_app_http_stream.cpp
  trunk/src/app/srs_app_http_stream.hpp
  trunk/src/app/srs_app_rtc_api.cpp
  trunk/src/app/srs_app_rtc_api.hpp
  trunk/src/app/srs_app_security.cpp
  trunk/src/app/srs_app_srt_conn.cpp
  trunk/src/app/srs_app_srt_conn.hpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#3910 RTC: Support OPUS stereo SDP option. v5.0.203 v6.0.105
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_rtc_source.hpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: TransByAI, RefinedByAI

#3854 Typo: line 263 - srs_app_srt_conn.cpp. v6.0.106
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_server.cpp
  trunk/src/app/srs_app_srt_conn.cpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#3911 WHIP: Fix bug for converting WHIP to RTMP/HLS. v5.0.204 v6.0.107
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_rtc_source.hpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/kernel/srs_kernel_rtc_rtp.cpp
  trunk/src/kernel/srs_kernel_rtc_rtp.hpp
Labels: RefinedByAI, EnglishNative

#3869 A demo for SRT proxy.
  trunk/research/srt-proxy/.gitignore
  trunk/research/srt-proxy/go.mod
  trunk/research/srt-proxy/main.go
Labels: EnglishNative

#3914 Forward: when unpublish crash caused by uninitialized forward connection. v6.0.107
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_forward.cpp
  trunk/src/core/srs_core_version6.hpp
Labels: TransByAI, RefinedByAI

#3916 Enhancing the compatibility of options.sh. v5.0.204 v6.0.108
  trunk/auto/options.sh
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: TransByAI, RefinedByAI
