Repository ossrs/srs, pull requests merged in 2023-09, with the labels that each got.

#3793 Remove unreachable issues in code
  trunk/src/app/srs_app_dvr.cpp
  trunk/src/app/srs_app_edge.cpp
  trunk/src/app/srs_app_ffmpeg.cpp
  trunk/src/app/srs_app_hls.cpp
  trunk/src/app/srs_app_recv_thread.hpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/kernel/srs_kernel_aac.cpp
  trunk/src/kernel/srs_kernel_ts.hpp
  trunk/src/main/srs_main_ingest_hls.cpp
  trunk/src/protocol/srs_protocol_http_stack.hpp
  trunk/src/protocol/srs_protocol_rtmp_stack.cpp
  trunk/src/protocol/srs_protocol_stream.hpp
Labels: EnglishNative

#3795 Fix dash crash if format not supported. v5.0.177 v6.0.73
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_dash.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: TransByAI, RefinedByAI

#3794 Support SRS Stack token for authentication. v6.0.74
  trunk/3rdparty/httpx-static/README.md
  trunk/3rdparty/srs-bench/gb28181/gb28181.go
  trunk/3rdparty/srs-bench/gb28181/gb28181_test.go
  trunk/3rdparty/srs-bench/gb28181/gb_test.go
  trunk/3rdparty/srs-bench/gb28181/ingester.go
  trunk/3rdparty/srs-bench/gb28181/ps.go
  trunk/3rdparty/srs-bench/gb28181/sip.go
  trunk/3rdparty/srs-bench/gb28181/util.go
  trunk/doc/CHANGELOG.md
  trunk/research/console/js/srs.console.js
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/kernel/srs_kernel_rtc_rtp.hpp
Labels: RefinedByAI, EnglishNative

#3804 Support FFmpeg timecode, fix AMF0 parsing failed. v5.0.179 v6.0.77
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_utility.cpp
  trunk/src/app/srs_app_utility.hpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/protocol/srs_protocol_rtmp_stack.cpp
  trunk/src/protocol/srs_protocol_utility.cpp
  trunk/src/protocol/srs_protocol_utility.hpp
Labels: RefinedByAI, EnglishNative

#3696 SRT: Log level to debug when no socket to accept. v5.0.180 v6.0.78
  trunk/3rdparty/patches/srt/api.cpp-01.patch
  trunk/auto/depends.sh
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#3807 Prevent the output of srt logs in utest. v5.0.181 v6.0.79
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/utest/srs_utest.cpp
Labels: RefinedByAI, EnglishNative

#3404 WebRTC: Support WHEP for play. v5.0.182 v6.0.80
  trunk/doc/CHANGELOG.md
  trunk/research/players/js/srs.page.js
  trunk/research/players/js/srs.sdk.js
  trunk/src/app/srs_app_rtc_api.cpp
  trunk/src/app/srs_app_rtc_server.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#3806 Build: Support sys-ssl for srt. v5.0.184 v6.0.82
  trunk/auto/depends.sh
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#3777 Build: Check __GLIBC__ for OpenHarmony to fix build fail. v6.0.83
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_threads.cpp
  trunk/src/core/srs_core_version6.hpp
Labels: TransByAI, RefinedByAI

#3810 Change dev code for John. v6.0.84
  README.md
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#3816 Cherry-pick from develop, for srt utest. v5.0.185
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_config.cpp
  trunk/src/app/srs_app_config.hpp
  trunk/src/app/srs_app_srt_server.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/protocol/srs_protocol_srt.cpp
  trunk/src/protocol/srs_protocol_srt.hpp
  trunk/src/utest/srs_utest_srt.cpp
Labels: RefinedByAI, EnglishNative
