Repository ossrs/srs, pull requests merged in 2023-10, with the labels that each got.

#3824 Solve the problem of inaccurate HLS TS duration. v5.0.187 v6.0.87
  Dockerfile
  trunk/conf/full.conf
  trunk/conf/hls.origin.conf
  trunk/conf/hls.realtime.conf
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_config.cpp
  trunk/src/app/srs_app_hls.cpp
  trunk/src/app/srs_app_hls.hpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/utest/srs_utest_config.cpp
Labels: RefinedByAI, EnglishNative

#3825 SRT: Fix the missing config mss. v5.0.188 v6.0.88
  trunk/conf/full.conf
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_config.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/utest/srs_utest_config.cpp
Labels: RefinedByAI, EnglishNative

#3827 Fix bug for upgrading to OpenSSL 3.0. v5.0.189 v6.0.89
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/protocol/srs_protocol_rtmp_handshake.cpp
Labels: RefinedByAI, EnglishNative

#3841 Refactor: Update the badge to SRS.
  trunk/research/console/en_index.html
  trunk/research/console/ng_index.html
Labels: RefinedByAI, EnglishNative

#3758 Refine docker detect mechenism. v5.0.190 v6.0.90
  Dockerfile
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_config.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/main/srs_main_server.cpp
Labels: TransByAI, RefinedByAI

#3840 Disable asan by default. v5.0.192 v6.0.92
  Dockerfile
  README.md
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#3846 Added system library option for ffmpeg, srtp, srt libraries. v5.0.193 v6.0.93
  trunk/auto/depends.sh
  trunk/auto/options.sh
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#3847 WebRTC: TCP transport should use read_fully instead of read. v5.0.194 v6.0.94
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtc_network.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI

#3845 RTC: Fix FFmpeg opus audio noisy issue. v5.0.195 v6.0.95
  trunk/auto/options.sh
  trunk/conf/rtc.tcp.only.conf
  trunk/conf/rtc.tcp.udp.conf
  trunk/doc/CHANGELOG.md
  trunk/ide/srs_clion/CMakeLists.txt
  trunk/src/app/srs_app_rtc_codec.cpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/protocol/srs_protocol_rtmp_handshake.cpp
Labels: RefinedByAI, EnglishNative
