Repository ossrs/srs, pull requests merged in 2024-07, with the labels that each got.

#4042 Refine config directive token parsing. v6.0.135
  trunk/conf/edge.token.traverse.conf
  trunk/conf/full.conf
  trunk/conf/http.heartbeat.conf
  trunk/doc/CHANGELOG.md
  trunk/scripts/verify_confs.sh
  trunk/src/app/srs_app_config.cpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/utest/srs_utest.cpp
  trunk/src/utest/srs_utest_config.cpp
Labels: RefinedByAI, EnglishNative

#4028 HTTPS: Support config key/cert for HTTPS API. v6.0.137
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_http_conn.cpp
  trunk/src/app/srs_app_http_conn.hpp
  trunk/src/app/srs_app_server.cpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#4111 DASH: Fix time unit error for disposing. v6.0.138
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_config.cpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#4126 Edge: Improve stability for state and fd closing. v5.0.214 v6.0.139
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_edge.cpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI

#4116 Dockerfile: Consistently use proper ENV syntax using equal sign. v6.0.140
  Dockerfile
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#4063 HTTP-TS: Support guess_has_av for audio only stream. v6.0.141
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_http_stream.cpp
  trunk/src/app/srs_app_http_stream.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/kernel/srs_kernel_ts.cpp
  trunk/src/kernel/srs_kernel_ts.hpp
Labels: RefinedByAI, EnglishNative

#4029 Player: Fix empty img tag occupy 20px size in safari. v6.0.142
  trunk/doc/CHANGELOG.md
  trunk/research/console/en_index.html
  trunk/research/console/ng_index.html
  trunk/research/players/rtc_player.html
  trunk/research/players/rtc_publisher.html
  trunk/research/players/srs_bwt.html
  trunk/research/players/srs_chat.html
  trunk/research/players/srs_gb28181.html
  trunk/research/players/srs_player.html
  trunk/research/players/srs_player_deprecated.html
  trunk/research/players/srs_publisher.html
  trunk/research/players/srs_publisher_flash.html
  trunk/research/players/vlc.html
  trunk/research/players/whep.html
  trunk/research/players/whip.html
  trunk/src/core/srs_core_version6.hpp
Labels: TransByAI, RefinedByAI

#4115 HLS: Add missing newline to end of session manifest. v6.0.143
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_http_static.cpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/utest/srs_utest_http.cpp
Labels: RefinedByAI, EnglishNative

#4101 GB28181: Support external SIP server. v6.0.144
  trunk/conf/full.conf
  trunk/conf/gb28181-without-sip.conf
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_gb28181.cpp
  trunk/src/app/srs_app_gb28181.hpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI, EnglishNative

#4127 Transcode: Support video codec such as h264_qsv and libx265. v6.0.145
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_ffmpeg.cpp
  trunk/src/core/srs_core_version6.hpp
Labels: RefinedByAI
