Repository ossrs/srs, pull requests merged in 2025-08, with the labels that each got.

#4432 AI: HTTP-FLV: Fix heap-use-after-free crash during stream unmount. v6.0.171 v7.0.50
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_http_stream.cpp
  trunk/src/app/srs_app_http_stream.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/core/srs_core_version7.hpp
Labels: RefinedByAI, EnglishNative, AI Handled

#4186 fix rtc listen port conflict for origin2/3 conf
  trunk/conf/origin2-for-proxy.conf
  trunk/conf/origin3-for-proxy.conf
Labels: ReadyToMerge, EnglishNative

#4225 HLS: Remove deprecated hls_acodec/hls_vcodec configs. v7.0.53
  trunk/conf/full.conf
  trunk/conf/mp3.conf
  trunk/conf/mp3.rtc.conf
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_config.cpp
  trunk/src/app/srs_app_config.hpp
  trunk/src/app/srs_app_hls.cpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/utest/srs_utest_config.cpp
  trunk/src/utest/srs_utest_fmp4.cpp
Labels: RefinedByAI, EnglishNative

#3126 HLS: restore HLS information when republish stream.(#3088). v7.0.57
  trunk/3rdparty/gtest-fit/CMakeLists.txt
  trunk/3rdparty/gtest-fit/googlemock/CMakeLists.txt
  trunk/3rdparty/gtest-fit/googletest/CMakeLists.txt
  trunk/conf/full.conf
  trunk/conf/hls.conf
  trunk/doc/CHANGELOG.md
  trunk/ide/srs_clion/CMakeLists.txt
  trunk/src/app/srs_app_config.cpp
  trunk/src/app/srs_app_config.hpp
  trunk/src/app/srs_app_hls.cpp
  trunk/src/app/srs_app_hls.hpp
  trunk/src/core/srs_core_version7.hpp
Labels: TransByAI, RefinedByAI

#4445 AI: Remove multi-threading support and change to single-thread architecture. v7.0.59
  trunk/auto/options.sh
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_circuit_breaker.cpp
  trunk/src/app/srs_app_circuit_breaker.hpp
  trunk/src/app/srs_app_hybrid.cpp
  trunk/src/app/srs_app_hybrid.hpp
  trunk/src/app/srs_app_log.cpp
  trunk/src/app/srs_app_log.hpp
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtc_queue.cpp
  trunk/src/app/srs_app_rtc_server.cpp
  trunk/src/app/srs_app_rtc_server.hpp
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_rtsp_conn.cpp
  trunk/src/app/srs_app_rtsp_source.cpp
  trunk/src/app/srs_app_threads.cpp
  trunk/src/app/srs_app_threads.hpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/main/srs_main_ingest_hls.cpp
  trunk/src/main/srs_main_server.cpp
  trunk/src/utest/srs_utest.cpp
Labels: RefinedByAI, EnglishNative

#4452 AI: Implement stream publish token system to prevent race conditions across all protocols. v7.0.62
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_dash.cpp
  trunk/src/app/srs_app_dvr.cpp
  trunk/src/app/srs_app_edge.cpp
  trunk/src/app/srs_app_hls.cpp
  trunk/src/app/srs_app_hybrid.cpp
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/app/srs_app_server.cpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/app/srs_app_srt_conn.cpp
  trunk/src/app/srs_app_stream_token.cpp
  trunk/src/app/srs_app_stream_token.hpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/kernel/srs_kernel_codec.cpp
  trunk/src/utest/srs_utest_stream_token.cpp
  trunk/src/utest/srs_utest_stream_token.hpp
Labels: RefinedByAI, EnglishNative

#4456 AI: Remove cloud CLS and APM. v7.0.66
  trunk/auto/auto_headers.sh
  trunk/auto/options.sh
  trunk/conf/full.conf
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_config.cpp
  trunk/src/app/srs_app_config.hpp
  trunk/src/app/srs_app_edge.cpp
  trunk/src/app/srs_app_edge.hpp
  trunk/src/app/srs_app_hybrid.cpp
  trunk/src/app/srs_app_latest_version.cpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/app/srs_app_rtmp_conn.hpp
  trunk/src/app/srs_app_statistic.cpp
  trunk/src/app/srs_app_tencentcloud.cpp
  trunk/src/app/srs_app_tencentcloud.hpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/main/srs_main_server.cpp
  trunk/src/utest/srs_utest_config.cpp
Labels: RefinedByAI, EnglishNative

#4458 AI: Remove most of reload, only keep framework.
  trunk/src/app/srs_app_config.cpp
  trunk/src/app/srs_app_config.hpp
  trunk/src/app/srs_app_recv_thread.cpp
  trunk/src/app/srs_app_recv_thread.hpp
  trunk/src/app/srs_app_reload.cpp
  trunk/src/app/srs_app_reload.hpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/app/srs_app_rtmp_conn.hpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/app/srs_app_source.hpp
  trunk/src/utest/srs_utest_reload.cpp
  trunk/src/utest/srs_utest_reload.hpp
Labels: EnglishNative

#4459 AI: Merge SRT and RTC servers into unified SrsServer. v7.0.68
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/modules/hls-ingester/config
  trunk/modules/mp4-parser/config
  trunk/modules/readme.txt
  trunk/src/app/srs_app_circuit_breaker.cpp
  trunk/src/app/srs_app_gb28181.cpp
  trunk/src/app/srs_app_gb28181.hpp
  trunk/src/app/srs_app_http_api.cpp
  trunk/src/app/srs_app_http_static.cpp
  trunk/src/app/srs_app_hybrid.cpp
  trunk/src/app/srs_app_hybrid.hpp
  trunk/src/app/srs_app_listener.cpp
  trunk/src/app/srs_app_listener.hpp
  trunk/src/app/srs_app_rtc_api.cpp
  trunk/src/app/srs_app_rtc_api.hpp
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtc_conn.hpp
  trunk/src/app/srs_app_rtc_network.cpp
  trunk/src/app/srs_app_rtc_server.cpp
  trunk/src/app/srs_app_rtc_server.hpp
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/app/srs_app_rtsp_source.cpp
  trunk/src/app/srs_app_server.cpp
  trunk/src/app/srs_app_server.hpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/app/srs_app_srt_conn.cpp
  trunk/src/app/srs_app_srt_conn.hpp
  trunk/src/app/srs_app_srt_server.cpp
  trunk/src/app/srs_app_srt_server.hpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/main/srs_main_ingest_hls.cpp
  trunk/src/main/srs_main_mp4_parser.cpp
  trunk/src/main/srs_main_server.cpp
  trunk/src/protocol/srs_protocol_srt.hpp
  trunk/src/protocol/srs_protocol_st.hpp
  trunk/src/utest/srs_utest.cpp
Labels: RefinedByAI, EnglishNative

#4460 AI: Always enable SRT protocol. v7.0.69
  trunk/auto/auto_headers.sh
  trunk/auto/depends.sh
  trunk/auto/options.sh
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_pithy_print.cpp
  trunk/src/app/srs_app_pithy_print.hpp
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/app/srs_app_server.cpp
  trunk/src/app/srs_app_server.hpp
  trunk/src/app/srs_app_srt_server.cpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/kernel/srs_kernel_kbps.cpp
  trunk/src/main/srs_main_server.cpp
  trunk/src/utest/srs_utest.cpp
Labels: RefinedByAI, EnglishNative

#4461 AI: Extract shared components and improve SRS server architecture. v7.0.70
  trunk/auto/options.sh
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_circuit_breaker.cpp
  trunk/src/app/srs_app_conn.cpp
  trunk/src/app/srs_app_conn.hpp
  trunk/src/app/srs_app_gb28181.cpp
  trunk/src/app/srs_app_gb28181.hpp
  trunk/src/app/srs_app_hourglass.cpp
  trunk/src/app/srs_app_hourglass.hpp
  trunk/src/app/srs_app_http_static.cpp
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtc_conn.hpp
  trunk/src/app/srs_app_rtc_server.cpp
  trunk/src/app/srs_app_rtc_server.hpp
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_server.cpp
  trunk/src/app/srs_app_server.hpp
  trunk/src/app/srs_app_srt_conn.cpp
  trunk/src/app/srs_app_srt_server.cpp
  trunk/src/app/srs_app_srt_server.hpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/kernel/srs_kernel_kbps.cpp
  trunk/src/kernel/srs_kernel_kbps.hpp
  trunk/src/main/srs_main_server.cpp
Labels: RefinedByAI, EnglishNative
