Repository ossrs/srs, pull requests merged in 2025-09, with the labels that each got.

#4462 HTTP: Rename HTTP hijack to dynamic match for better clarity. v7.0.71
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_http_stream.cpp
  trunk/src/app/srs_app_http_stream.hpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/kernel/srs_kernel_error.hpp
  trunk/src/protocol/srs_protocol_http_stack.cpp
  trunk/src/protocol/srs_protocol_http_stack.hpp
  trunk/src/utest/srs_utest_http.cpp
  trunk/src/utest/srs_utest_st.cpp
Labels: RefinedByAI, EnglishNative

#4464 AI: Update RTMP message memory management with shared pointers. v7.0.73
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_dash.cpp
  trunk/src/app/srs_app_dvr.cpp
  trunk/src/app/srs_app_edge.cpp
  trunk/src/app/srs_app_forward.cpp
  trunk/src/app/srs_app_gb28181.cpp
  trunk/src/app/srs_app_hds.cpp
  trunk/src/app/srs_app_http_stream.cpp
  trunk/src/app/srs_app_mpegts_udp.cpp
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_rtsp_source.cpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/app/srs_app_srt_source.cpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/kernel/srs_kernel_buffer.cpp
  trunk/src/kernel/srs_kernel_buffer.hpp
  trunk/src/kernel/srs_kernel_flv.cpp
  trunk/src/kernel/srs_kernel_flv.hpp
  trunk/src/kernel/srs_kernel_kbps.cpp
  trunk/src/kernel/srs_kernel_rtc_rtp.cpp
  trunk/src/kernel/srs_kernel_rtc_rtp.hpp
  trunk/src/protocol/srs_protocol_format.cpp
  trunk/src/protocol/srs_protocol_rtmp_stack.cpp
  trunk/src/protocol/srs_protocol_rtmp_stack.hpp
  trunk/src/protocol/srs_protocol_rtp.cpp
  trunk/src/utest/srs_utest_fmp4.cpp
  trunk/src/utest/srs_utest_kernel.cpp
  trunk/src/utest/srs_utest_protocol.cpp
  trunk/src/utest/srs_utest_rtmp.cpp
Labels: RefinedByAI, EnglishNative

#4469 Upgrade HTTP parser from http-parser to llhttp. v7.0.77
  trunk/conf/full.conf
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version7.hpp
  trunk/src/protocol/srs_protocol_http_conn.cpp
  trunk/src/protocol/srs_protocol_http_conn.hpp
  trunk/src/protocol/srs_protocol_http_stack.cpp
  trunk/src/protocol/srs_protocol_http_stack.hpp
  trunk/src/protocol/srs_protocol_http_stack_llhttp.cpp
  trunk/src/protocol/srs_protocol_http_stack_llhttp.hpp
  trunk/src/protocol/srs_protocol_http_stack_llhttpadapter.cpp
  trunk/src/protocol/srs_protocol_http_stack_llhttpadapter.hpp
  trunk/src/protocol/srs_protocol_http_stack_llhttpapi.cpp
  trunk/src/protocol/srs_protocol_http_stack_llhttpapi.hpp
  trunk/src/protocol/srs_protocol_http_stack_llhttphttp.cpp
  trunk/src/protocol/srs_protocol_http_stack_llhttphttp.hpp
  trunk/src/utest/srs_utest_http.cpp
  trunk/src/utest/srs_utest_protocol2.cpp
  trunk/src/utest/srs_utest_service.cpp
Labels: RefinedByAI, EnglishNative

#4467 WebRTC: Fix NACK recovered packets not being added to receive queue. v7.0.78
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/utest/srs_utest_rtc_recv_track.cpp
  trunk/src/utest/srs_utest_rtc_recv_track.hpp
Labels: RefinedByAI, EnglishNative, AI Handled

#4474 WebRTC: Fix race condition in RTC nack timer callbacks. v7.0.79
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtc_conn.hpp
  trunk/src/core/srs_core_version7.hpp
Labels: RefinedByAI, EnglishNative

#4475 AI: Support anonymous coroutine with code block. v7.0.80
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_async_call.cpp
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_rtsp_source.cpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/app/srs_app_srt_source.cpp
  trunk/src/app/srs_app_stream_token.cpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/protocol/srs_protocol_st.cpp
  trunk/src/protocol/srs_protocol_st.hpp
  trunk/src/utest/srs_utest.cpp
  trunk/src/utest/srs_utest.hpp
  trunk/src/utest/srs_utest_st.cpp
  trunk/src/utest/srs_utest_st2.cpp
  trunk/src/utest/srs_utest_st2.hpp
Labels: RefinedByAI, EnglishNative

#4478 AI: Add more utests for kernel module. v7.0.81
  .augment-guidelines
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_edge.cpp
  trunk/src/app/srs_app_edge.hpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/app/srs_app_source.hpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/kernel/srs_kernel_balance.cpp
  trunk/src/kernel/srs_kernel_balance.hpp
  trunk/src/kernel/srs_kernel_buffer.cpp
  trunk/src/kernel/srs_kernel_buffer.hpp
  trunk/src/utest/srs_utest_core.cpp
  trunk/src/utest/srs_utest_kernel.cpp
  trunk/src/utest/srs_utest_kernel2.cpp
Labels: RefinedByAI, EnglishNative

#4446 SRT2RTMP: fix srt bridge hevc to rtmp error. v7.0.84
  trunk/3rdparty/srs-bench/blackbox/hevc_test.go
  trunk/3rdparty/srs-bench/blackbox/util.go
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_srt_source.cpp
  trunk/src/core/srs_core_version7.hpp
Labels: RefinedByAI

#4489 Improve coverage for kernel. v7.0.88
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version7.hpp
  trunk/src/utest/srs_utest_kernel3.cpp
Labels: RefinedByAI, EnglishNative

#4491 RTC2RTMP: Fix sequence number wraparound assertion crashes. v6.0.177
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/utest/srs_utest_rtc.cpp
Labels: EnglishNative

#4505 improve blackbox test for rtsp. v7.0.93
  trunk/3rdparty/srs-bench/blackbox/rtsp_test.go
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version7.hpp
  trunk/src/utest/srs_utest_app3.cpp
  trunk/src/utest/srs_utest_app4.cpp
  trunk/src/utest/srs_utest_app4.hpp
Labels: RefinedByAI, EnglishNative

#4506 rename HEVC-related mux functions to enhance consistency and readability.
  trunk/src/app/srs_app_gb28181.cpp
  trunk/src/app/srs_app_rtc_source.cpp
  trunk/src/app/srs_app_srt_source.cpp
  trunk/src/protocol/srs_protocol_raw_avc.cpp
  trunk/src/protocol/srs_protocol_raw_avc.hpp
  trunk/src/utest/srs_utest_protocol3.cpp
Labels: EnglishNative

#4512 For Edge, only support RTMP or HTTP-FLV. 6.0.179
  trunk/conf/edge.conf
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtc_api.cpp
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/app/srs_app_source.cpp
  trunk/src/app/srs_app_srt_conn.cpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/utest/srs_utest_config.cpp
Labels: EnglishNative

#4513 For Edge, only support RTMP or HTTP-FLV. v7.0.94
  trunk/conf/edge.conf
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtc_api.cpp
  trunk/src/app/srs_app_rtc_conn.cpp
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/app/srs_app_rtmp_source.cpp
  trunk/src/app/srs_app_srt_conn.cpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/utest/srs_utest_app7.cpp
Labels: RefinedByAI, EnglishNative
