Repository ossrs/srs, pull requests merged in 2025-03, with the labels that each got.

#4296 Dvr: support h265 flv fragments. v6.0.162 v7.0.24
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_dvr.cpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/core/srs_core_version7.hpp
Labels: TransByAI, RefinedByAI

#4302 update geekyeggo/delete-artifact to 5.0.0. v5.0.221 v6.0.163 v7.0.25
  .github/workflows/test.yml
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/core/srs_core_version7.hpp
Labels: TransByAI, RefinedByAI

#4305 free sample to prevent memory leak. v5.0.222 v6.0.164 v7.0.26
  trunk/doc/CHANGELOG.md
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/core/srs_core_version7.hpp
  trunk/src/kernel/srs_kernel_rtc_rtp.cpp
Labels: RefinedByAI, EnglishNative

#4303 replace values with enums. v6.0.166 v7.0.28
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_rtmp_conn.cpp
  trunk/src/core/srs_core_version5.hpp
  trunk/src/core/srs_core_version6.hpp
  trunk/src/core/srs_core_version7.hpp
Labels: ReadyToMerge, RefinedByAI, EnglishNative

#4294 Build: update build version to v7. v7.0.29
  trunk/auto/options.sh
  trunk/auto/summary.sh
  trunk/configure
  trunk/doc/CHANGELOG.md
  trunk/ide/srs_clion/CMakeLists.txt
  trunk/src/core/srs_core_version7.hpp
Labels: ReadyToMerge, RefinedByAI, EnglishNative

#4292 Typo: "forked" process in log output. v7.0.30
  trunk/doc/CHANGELOG.md
  trunk/src/app/srs_app_process.cpp
  trunk/src/core/srs_core_version7.hpp
Labels: ReadyToMerge, RefinedByAI, EnglishNative
